### ISSUE TITLE
worker job id

### ISSUE THREAD

**Issue by jdupl123** [cdrx/faktory_worker_python#13]
I run the folowing example

```
from faktory import Worker
import logging
import time


def your_function(x, y):
    time.sleep(15)
    return x + y


w = Worker(queues=['default'], concurrency=1)
w.register('test', your_function)
print(w.get_worker_id())
logging.basicConfig(level=logging.DEBUG)
w.run()  # runs until control-c or worker shutdown from Faktory web UI
```

worker id prints as 32860cb098ae4e13ab8a7f44af498bf1
but heartbeat shows 
DEBUG:faktory.worker:Sending heartbeat for worker 9e9775cb1abc47b7b6c6bc1ec6689610

looking in the web interface it seem that the debug message contains the correct id.

**Comment by cdrx** [comment]
`w.worker_id` will give you the worker's actual id 

`get_worker_id()` is poorly named, it should be called something like `generate_random_worker_id()`

**Comment by jdupl123** [comment]
thanks for reply 👍
