### ISSUE TITLE
Priority isn't sent to faktory when queuing a job

### ISSUE THREAD

**Issue by cdrx** [cdrx/faktory_worker_python#2]

**Comment by Schniz** [comment]
I believe it belongs here:

https://github.com/cdrx/faktory_worker_python/blob/a87f43815ba7db526ca4c68edf56534ef5306f82/faktory/client.py#L46-L50

adding a `'priority': priority`, but I can't test it right now. I'll try it and make a PR if it actually works.

**Comment by cdrx** [comment]
👍
