### ISSUE TITLE
Single arg as array

### ISSUE THREAD

**Issue by rvillas** [cdrx/faktory_worker_python#3]
I am working with go and python and for a python call to work with go, when there is only one argument, you should pass this argument as array (or it will accuse an error from the go - string to [] interface {}).

I do not understand much of python so I do not know if it is easier to update the documentation or test when the argument is a single arg.

Great job, by the way :-)

`
  with faktory.connection() as client:
    client.queue('some_job', args=([single_argument]), queue='some_job')
`

**Comment by cdrx** [comment]
The `args` always has to be an iterable.

In Python, a brackets don't make an array, you need a trailing comma; eg:

```
client.queue('some_job', args=(single_argument, ), queue='some_job')
```

if you use the list syntax [] rather than tuple syntax () then you don't need the trailing comma:

```
client.queue('some_job', args=[single_argument], queue='some_job')
```

Because `()` isn't a tuple, then `([single_argument])` and `[single_argument]` are equal.

**Comment by Schniz** [comment]
what about `client.queue('some_job', args={"key": "value"}, queue='some_job')`?
I believe it won't be interpreted as kwargs, therefore you we shouldn't accept _any_ iterable. `Union(Set, List, Tuple)` sounds like a good coverage. What do you think?

**Comment by cdrx** [comment]
Faktory wont accept a dict for job args, though it would be nice if it did. It needs to be something that can be deserialised to a slice in Go. 

Python's `json` won't serialise a set type, so we should probably pass `args` through `list(..)` to exhaust anything thats iterable before sending to faktory.

That does mean that `args={"key": "value"}` will be sent to faktory as `args=("key")` though.

**Comment by Schniz** [comment]
So the only reason to not raise an error if something other than `list` or `tuple` is to support generators?
I believe you can test `typing.Iterator` to catch generators. IMO, any other types, including `dict` should raise an error
