### ISSUE TITLE
Example worker restarting itself on 3.9

### ISSUE THREAD

**Issue by edmz** [cdrx/faktory_worker_python#33]
**What I'm I seeing:**

When running the sample code it seems like the worker crashes/restarts itself without the registered function being called.

**What I'm expecting:**

For the registered function to be ran.

**What I'm doing:**

I have some code that I've been running without problem on 4 different macs. This is the first time I try to run in on an m1. All of the other macs have python 3.7, this one has 3.9. Other than that everything remained the same. I tried to remove as much code from my working project to try to reproduce this but it then ocurred to me to use the sample code from the readme. And it behaves the same.

What I did is I added some print statements to that code and ran it:

``` python
from faktory import Worker

def your_function(x, y):
    print("running your_function")
    return x + y

w = Worker(queues=['default'], concurrency=1)
w.register('test', your_function)
print("after register")
w.run()  # runs until control-c or worker shutdown from Faktory web UI
```

After running the example server code I get on the terminal the expected output:

```
after register
```

...but if I use the client code to send a job to be executed now the console shows this:

```
after register
after register
```

Like the whole code is being run again and the function is not executed.

Any ideas on how to debug this are appreciated. 

Thank you

**Comment by cdrx** [comment]
Does it work if you pass `use_threads=True` to the `Worker` class?

I don't have access to an M1 Mac so I can't debug this. Python support in 3.9.1 is experimental only. Are you able to test on one of the Python 3.10 alphas?

**Comment by edmz** [comment]
> Does it work if you pass `use_threads=True` to the `Worker` class?

Yes it did.

> I don't have access to an M1 Mac so I can't debug this. Python support in 3.9.1 is experimental only. Are you able to test on one of the Python 3.10 alphas?

I'm installing everything via brew. I will check if it's available and let you know.

**Comment by edmz** [comment]
I haven't had the time to install 3.10 alphas but brew has 3.8 that runs on the M1. One of my tests I managed to get this error:

> RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase. This probably means that you are not using fork to start your child processes and you have forgotten to use the proper idiom in the main module: if __name__ == '__main__': freeze_support() ... The "freeze_support()" line can be omitted if the program is not going to be frozen to produce an executable.

So I modified it the sample code to:

``` python

from faktory import Worker

def your_function(x, y):
    print("your_function")
    return x + y


if __name__ == '__main__':
  w = Worker(queues=['default'], concurrency=1, use_threads=False)
  w.register('test', your_function)
  print("after_register")
  w.run()  # runs until control-c or worker shutdown from Faktory web UI
```

And it works now (the sample code, but sadly not mine yet). Does this give you any ideas on where the issue could lie or where I can investigate further?

Thank you.

**Comment by edmz** [comment]
Forgot to mention that adding that `if` makes the sample code also work under 3.9.

**Comment by cdrx** [comment]
If I understand correctly, adding `if __name__ == '__main__':` fixes the sample code, but not your production code? If so, I'll update the readme. 

Could you try adding:

```py
multiprocessing.set_start_method("fork", force=True)
```

and see if that helps at all?

**Comment by edmz** [comment]
> ```python
> multiprocessing.set_start_method("fork", force=True)
> ```

I changed that and some jobs run, others fail with a `BrokenPipe [ErrNo 32]` error (which is shown in Faktory's UI). This is the code that I'm currently running (as a test case):

``` python
import sys
from faktory import Worker
import time
import logging
import os
import multiprocessing

multiprocessing.set_start_method("fork", force=True)

print("after import")

def myfunc(phone, amount, params = {}):
  time.sleep(1)
  print("myfunc")

if __name__ == '__main__':
  print("entering main")
  w = Worker(queues=['foo'], concurrency=3)
  w.register('FooJob', myfunc)
  w.run()
```

I tried changing the concurrency to 1, but the effect was the same. Sometimes it runs, other times I get the BrokenPipe error.
