### ISSUE TITLE
ImportError: cannot import name 'BrokenThreadPool' for python version less than 3.7

### ISSUE THREAD

**Issue by ItsAnkit** [cdrx/faktory_worker_python#35]
We are using faktory in our flask app. Our testcases started failing recently with following error: 
**ImportError: cannot import name 'BrokenThreadPool'**

![image](https://user-images.githubusercontent.com/24620862/112133385-a796f700-8bf1-11eb-818a-c64ed385e0d0.png)

I came across this [https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.thread.BrokenThreadPool](url) mentioning BrokerThreadPool is new in python 3.7. 

![image](https://user-images.githubusercontent.com/24620862/112134084-59362800-8bf2-11eb-886f-dd9972908dcf.png)

Can somebody help me with this?

**Comment by cdrx** [comment]
Upgrade to Python 3.7 or downgrade this package to version 0.4 which supports Python 3.5 onwards.
