### ISSUE TITLE
Flag version >0.5 to only be python 3.7+ compatible

### ISSUE THREAD

**Issue by joosterman** [cdrx/faktory_worker_python#36]
In https://github.com/cdrx/faktory_worker_python/commit/1b9eff38bbf539ba254bfba7e68adc2cc5c2770e#diff-7cbedbf1bd8665e9c89414493ca105c611bc434c823bb9cce75867e35075c82dR12 the `BrokenThreadPool` was introduced.

This Exception was introduced in Python 3.7 https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.thread.BrokenThreadPool

The package should indicate that requires Python 3.7+ with https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

**Comment by joosterman** [comment]
@cdrx Shall I make a PR for this?

**Comment by cdrx** [comment]
Yes, please. I would gladly merge it.
