### ISSUE TITLE
Explaination on the thread execution model

### ISSUE THREAD

**Issue by antoine-gallix** [cdrx/faktory_worker_python#47]
The worker has the option to choose threads over processes for it's concurrent execution model. But how does it exactly work? For `n` being the number of concurrent jobs, does it means that `n` threads are started when the worker starts, and that those same three threads will be processing multiple jobs without restarting (model 1) ? Or does it means that each new job will start it's own thread that is closed at the end of it, up to a maximum of `n` threads simultaneously (model 2)?

I am using thread-local global variables, that I expected to be created anew at each job execution (model 2), but from my debugging, I start to suspect that threads processes multiple tasks in a row without restarting (model 1).

Can you confirm/infirm my conclusion?

**Comment by cdrx** [comment]
The worker uses [`concurrent.ThreadPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#threadpoolexecutor)

A maximum of `n` threads are created, where `n` == the `concurrency` argument for the `Worker` class.

Threads are reused for multiple jobs, so the behaviour should be model 1.

`threading.local()` will persist between job executions.

**Comment by antoine-gallix** [comment]
by the way, I would like to document that. where do you suggest that would go? in the docstring of the worker class or in the readme?

**Comment by cdrx** [comment]
I think the readme would be best for that. Thanks.
